### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by Peter2090** [nitrocaster/SkeinFish#9]
The following tests are failing:
TestThreefish1024Cbc
TestThreefish1024Ecb
TestThreefish1024Nist00
TestThreefish1024Nist01
TestThreefish256Cbc
TestThreefish256Cfb1
TestThreefish256Ecb
TestThreefish256Nist00
TestThreefish256Nist01
TestThreefish256Ofb1
TestThreefish512Cbc
TestThreefish512Ecb
TestThreefish512Nist00
TestThreefish512Nist01

**Comment by nitrocaster** [comment]
Oh my bad. That's a part of #8 actually.
